version: 0.0
os: linux
files:
  - source: /target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: scripts/stopTask.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: ubuntu